services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=postgres
      - POSTGRES_DB=zoudb
    volumes:
      - ${DOCKER_VOLUME_ROOT}/db_data:/var/lib/postgresql/data
    expose:
      - 5432
  redis:
    image: redis
    restart: always
    expose:
      - 6379

  zou-api:
    restart: always
    image: postwork-io/zou:latest
    build:
      context: .
      dockerfile: zou.dockerfile
    env_file:
      - stack.env
    environment:
      - ENABLE_JOB_QUEUE=True
      - PATH=/opt/zou/zouenv/bin:/usr/bin
    volumes:
      - ${DOCKER_VOLUME_ROOT}/zou_previews:/opt/zou/previews
      - ${DOCKER_VOLUME_ROOT}/tmp:/opt/zou/tmp
      - ${DOCKER_VOLUME_ROOT}/logs:/opt/zou/logs
    expose:
      - 5000
    command: api
    depends_on:
      - db
      - redis

  zou-events:
    restart: always
    image: postwork-io/zou:latest
    build:
      context: .
      dockerfile: zou.dockerfile
    env_file:
      - stack.env
    environment:
      - PATH=/opt/zou/zouenv/bin
    volumes:
      - ${DOCKER_VOLUME_ROOT}/zou_previews:/opt/zou/previews
      - ${DOCKER_VOLUME_ROOT}/tmp:/opt/zou/tmp
      - ${DOCKER_VOLUME_ROOT}/logs:/opt/zou/logs
    expose:
      - 5001
    command: events
    depends_on:
      - zou-api

  zou-worker:
    restart: always
    image: postwork-io/zou:latest
    build:
      context: .
      dockerfile: zou.dockerfile
    env_file:
      - stack.env
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    volumes:
      - ${DOCKER_VOLUME_ROOT}/zou_previews:/opt/zou/previews
      - ${DOCKER_VOLUME_ROOT}/tmp:/opt/zou/tmp
      - ${DOCKER_VOLUME_ROOT}/logs:/opt/zou/logs
    command: worker
    depends_on:
      - zou-api
      - redis
  kitsu:
    restart: always
    build:
      context: .
      dockerfile: kitsu.dockerfile
    ports:
      - 7000:80
      - 7443:443
